<a href="https://colab.research.google.com/github/ErabellySreeja2005/2303A51905-batch-28-/blob/main/Lab%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.random.seed(42)  # for reproducibility
scores = np.random.randint(50, 101, size=(4, 4))
print("Test Scores (4x4 Matrix):\n", scores)
row_mean = np.mean(scores, axis=1)
col_mean = np.mean(scores, axis=0)
print("\nRow-wise Means:", row_mean)
print("Column-wise Means:", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation (overall):", std_dev)
print("Variance (overall):", variance)
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

print("\nGlobal Maximum:", global_max, "at index", max_index)
print("Global Minimum:", global_min, "at index", min_index)
median_value = np.median(scores)
print("\nMedian Score:", median_value)

Test Scores (4x4 Matrix):
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]]

Row-wise Means: [80.5  70.75 66.25 74.75]
Column-wise Means: [75.5  74.25 71.25 71.25]

Standard Deviation (overall): 12.214073593605043
Variance (overall): 149.18359375

Global Maximum: 92 at index (np.int64(0), np.int64(3))
Global Minimum: 52 at index (np.int64(3), np.int64(3))

Median Score: 72.5
